### ISSUE TITLE
SC Lib Compile error

### ISSUE THREAD

**Issue by KonVas** [crucialfelix/crucial-library#12]
The problem insists but sporadically, so there are no standard steps to reproduce. When I recompile I run some code but I get Library not compiled. After couple of times trying to recompile it works. Here is the post window:

`compiling class library...
...
	Found 714 primitives.
	Compiling directory '/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/Extensions'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/Vowel'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/Dirt-Samples'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/SuperDirt'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/Canvas3D'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/XML'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/wslib'
	Compiling directory '/Users/konstantinos/.atom/packages/supercollider/node_modules/supercolliderjs/lib/supercollider-js'
ERROR: Class extension for nonexistent class 'Document'
     In file:'../../../../../../Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/wslib/wslib-classes/Lang/Workflow/extDocument-openStartup.sc'
ERROR: Class extension for nonexistent class 'Document'
     In file:'../../../../../../Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/wslib/wslib-classes/Lang/Workflow/extDocument-closeAllHelp.sc'
	numentries = 1412679 / 25812000 = 0.055
	7170 method selectors, 3600 classes
	method table size 24736448 bytes, big table size 206496000
	Number of Symbols 18024
	Byte Code Size 642528
	compiled 697 files in 8.85 seconds

Info: 8 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done

localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.02 seconds
compileError
`
Not entirely sure this is related: " Class extension for nonexistent class 'Document'"

**Comment by crucialfelix** [comment]
It doesn't look you have crucial-library installed at all. You do have supercollider-js in there, I can see that you have Atom Supercollider running. Did you intend to submit this bug there ?

In any case it does compile, as it says "compile done".  Those are nonexistent class messages are warnings, but the library does compile.

I don't know why it laster says compileError.  Are you unable to do anything after that ? Is this an atom supercollider problem you are having ?
