### ISSUE TITLE
Instr.loadAll not changed to new quarks system yet

### ISSUE THREAD

**Issue by sebshader** [crucialfelix/crucial-library#8]
when using Instr.loadAll it still searches extensions/quarks/*/Instr which doesn't seem to exist

**Comment by crucialfelix** [comment]
ah true. it has to get the includePaths from LanguageConfig

**Comment by jamshark70** [comment]
This issue has resurfaced on the mailing list.

http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Instr-loadAll-doesn-t-work-as-expected-what-happened-to-PlayerPool-tp7636787.html
